### ISSUE TITLE
Inconsistent date format in Master table

### ISSUE THREAD

**Issue by MonkmanMH** [cdalzell/Lahman#16]
In the table `Master` two of the date fields (`debut` and `finalGame`) the dates are represented inconsistently. For the dates prior to January 1, 1900 the dates are shown as yyyy-mm-dd (i.e. following the ISO 8601 standard). For dates after that, they are in m/d/yyyy.

(Note that a third date field in the table, `birthDate`, is in yyyy-mm-dd.)

This issue exists in the source csv version the Lahman database (version 2015), and is not peculiar to the R version.

I have not checked other tables at this point.

**Comment by MonkmanMH** [comment]
Gist of a quick fix work-around, which creates two new variables `debut_date` and `finalGame_date`

[https://gist.github.com/MonkmanMH/cf6b8b2dda385536f010](https://gist.github.com/MonkmanMH/cf6b8b2dda385536f010)

**Comment by friendly** [comment]
I think this is a case where, if we do anything other than documenting this problem (as here),
it is preferable to fix the data, rather than to introduce two new variables.  

All dates should be in the same format, and I suggest yyyy-mm-dd.

**Comment by djmurphy420** [comment]
I agree with Michael: if a problem arises in the database, it should be brought to Sean's attention. Since I'm sure his team is in the process of building the 2015 database right now (in past years, it has been released sometime between mid-January to early February), this should be done sooner rather than later.  

    On Wednesday, January 6, 2016 6:29 AM, Michael Friendly <notifications@github.com> wrote:
 

 I think this is a case where, if we do anything other than documenting this problem (as here),
it is preferable to fix the data, rather than to introduce two new variables. All dates should be in the same format, and I suggest yyyy-mm-dd.—

**Comment by djmurphy420** [comment]
I just checked - the only table which contains YMD dates is Master, which makes sense since all of the baseball-related tables are season summaries. 

    On Wednesday, January 6, 2016 7:52 AM, Dennis Murphy <djmurphy0420@yahoo.com> wrote:
 

 I agree with Michael: if a problem arises in the database, it should be brought to Sean's attention. Since I'm sure his team is in the process of building the 2015 database right now (in past years, it has been released sometime between mid-January to early February), this should be done sooner rather than later.  

    On Wednesday, January 6, 2016 6:29 AM, Michael Friendly <notifications@github.com> wrote:
 

 I think this is a case where, if we do anything other than documenting this problem (as here),
it is preferable to fix the data, rather than to introduce two new variables. All dates should be in the same format, and I suggest yyyy-mm-dd.—

**Comment by MonkmanMH** [comment]
I have sent a note with the issue directly to Sean Lahman via the database site.  I have also seen him comment on other issues in this repo, so perhaps he's already seen it  8-)

**Comment by seanlahman** [comment]
This issue can be closed.  Just so folks know, debut and final game are dates in the format yyyy-mm-dd.  We did this because some applications have difficulty handling dates before 1900, and for those users, this allows them the option of importing these fields as text.  For birth date and death date, we have separate fields for year, month and day, because there are instances where we only know the year or only know the month and the year. That would never be the case for debut or final game.

**Comment by MonkmanMH** [comment]
Thanks Sean! This issue is now closed.
