### ISSUE TITLE
replace plyr with dplyr; add dplyr examples

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#20]
dplyr is now so much better than plyr that the examples using the latter should be replaced with dplyr. For the most part,  I think this entails just using

```
library(dplyr)
```

rather than 

```
library(plyr)
```

in examples, but this should be checked.  Also, requires change in `DESCRIPTION` -- `Suggests:`  

As well, further useful examples of dplyr could be added.  Some examples of queries on the `Batting` table are given in `vignette("window-functions", package="dplyr")`.

**Comment by friendly** [comment]
`SeriesPost.Rd` and `TeamsFranchises.Rd` now use dplyr (thx: @MonkmanMH), so consequently, `dplyr` was added to `Suggests:`.

However, the examples using dplyr should be re-written, because they use some plyr constructs (like `colwise()`) that are unnecessary, and unavailable in dplyr.

**Comment by friendly** [comment]
For now, I added a demo, `demo/lahman-dplyr.R` showing a few things.

**Comment by djmurphy420** [comment]
Hi guys:
I'm working on updating the plyr examples to dplyr - should have it finished by tonight or tomorrow afternoon at the latest. For now, I'm putting the code in script files outside the repository while I'm testing it, but eventually I'll want to replace the old example code with the new ones in the .Rd files and push them to my forked repo on Github. Do you want me to commit to my fork and provide a pull request for each help file? I don't really want to commit every few lines or so because the changes in certain help pages are pretty extensive. Given that a commit to CRAN appears to be on the front burner, it just seems faster to commit a help page at a time or in bulk.
What are your preferences?
Dennis 

    On Wednesday, August 10, 2016 6:25 AM, Michael Friendly <notifications@github.com> wrote:
 

 For now, I added a demo, demo/lahman-dplyr.R showing a few things.—

**Comment by djmurphy420** [comment]
Hi Chris:
Thanks for the heads-up re timing. I have several of the code example files done - I can send them to you and you can tell me how you want to proceed. I have some experience with Github but it tends to be sporadic. Given the extent of the changes, it seems inefficient if I make a half-dozen pull requiests for one help file.
Right now I'm rewriting the example code that involves plyr and putting them into separate script files, one per affected help page. This allows me to test out the code and note any issues that arise (e.g., warnings).  I'll work on that today - if you (or anyone else) has any suggestions, let me know soon :)
Dennis 

    On Thursday, August 11, 2016 4:49 AM, Chris Dalzell <notifications@github.com> wrote:
 

 Looking at my schedule I can't imagine it'll be before the weekend that I'm able to submit to CRAN, so you've got time. :) Even if I need to hold off until sometime next week that's fine too.As for your changes, go ahead and make them in the feature/dplyr-update (https://github.com/cdalzell/Lahman/tree/feature/dplyr-update) branch that I just created. Once everything's in, let me know and I'll get it merged everywhere it needs to be.Thanks!—

**Comment by friendly** [comment]
That's a good strategy -- using a new branch, `feature/dplyr-update`, based on `develop`.   That way @djmurphy420 can test scripts separately, then incorporate them into the .Rd files.  You can make any number of commits, but save pull requests for when you have a stable collection that accomplishes some task.
