### ISSUE TITLE
2017 data update

### ISSUE THREAD

**Issue by rcammisola** [cdalzell/Lahman#38]
Hi,

I wanted to try and update the data so that it included the 2017 season.
It seems Sean hasn't had a chance to upload to his site yet, but mentioned that the CSV files exist on github (https://twitter.com/seanlahman/status/974796328130744320)

They're at this location: https://github.com/chadwickbureau/baseballdatabank/

I was going to try and open a PR to add these in. It seems I should be trying to use the inst/scripts to ensure they're correctly saved as Rdata files and appropriate columns set to factors. Is that correct?

**Comment by friendly** [comment]
We usually do our updates to the R package in the summer, after the dust has settled down, because there are often errors that get corrected after Sean releases the data for the new season.

But the process of updating takes a bit of work, using the scripts in `inst/scripts`.  It is not fully automatic, because sometimes the structure of one or more files has changed.  We create a new branch for this work, and @cdalzell now performs the update

**Comment by rcammisola** [comment]
Ok, no worries.
Thanks very much for getting back to me, I look forward to the update

**Comment by beanumber** [comment]
+1 on this! :smile:
