### ISSUE TITLE
CRAN version of Lahman requires 3.5

### ISSUE THREAD

**Issue by hadley** [cdalzell/Lahman#58]
Which is breaking our dplyr automated checks which we test on 3.3 and 3.4. But the [DESCRIPTION in this repo](https://github.com/cdalzell/Lahman/blob/master/DESCRIPTION) only mentions 2.10, so I'm a little mystified.

**Comment by friendly** [comment]
Ugh. This `requires 3.5` was occasioned by warnings we got in checking the package, something to do with loading data sets from the package and said that R version 3.5 now required.

I too am mystified that DESCRIPTION only mentions 2.10, and I can't find a reference to R 3.5, except in the README.md and in several revdep check files.

**Comment by hadley** [comment]
If the reasons is to do with data, that likely means that you need to set `version = 2` when you use `saveRDS()` to create the binary data files.

**Comment by cdalzell** [comment]
I've set the version for the data files to 2: https://github.com/cdalzell/Lahman/commit/7f327b7c934a330db2c1a141cdf5889159ec67ab#diff-4cb7dbd79f9710c22e524ef2f68ff753ccfda3a413ea98878bce75184fd5d640

Seems that `save` defaults to 3 and while `resaveRdaFiles` still defaults to 2 I set the value there just in case.

@hadley Is there an easy way that you can run checks against this branch? I ask because due to the size of this package CRAN submission can be challenging.

**Comment by hadley** [comment]
The only things I do other than running R CMD check locally are `devtools::check_win_devel()` and `devtools::check_rhub()`

**Comment by hadley** [comment]
I think all fixing this requires is merging "hotfix/58-dplyr_checks" and then releasing to CRAN again. Please let me know if there's anything I can do to help.

**Comment by friendly** [comment]
@cdalzell I've reviewed this merge request and it seems to be something we should have done a while ago.

I can do the merge, and then bump the pkg version. But it is up to you to release it to CRAN.

**Comment by cdalzell** [comment]
Update has been submitted to CRAN! I'll follow up here once it's published.

**Comment by hadley** [comment]
Thank you!

**Comment by cdalzell** [comment]
Hey all, took a bit but the update is now published on CRAN: https://cran.r-project.org/web/packages/Lahman/Lahman.pdf
