### ISSUE TITLE
Appearances Example Returns Bad Data

### ISSUE THREAD

**Issue by cdalzell** [cdalzell/Lahman#7]
The last example in appearances doc returns 207 players as having played 162 games that season, only four of whom have a player ID associated with them. The rest are NA.

This can be reproduced in the current version available on CRAN (3.0-1)

This will reproduce the issue:
```
all162 <- ddply(subset(Appearances, yearID > 1960), .(yearID),
                         summarise, allGamers = playerID[G_all == 162])
table(all162$yearID)
```

**Comment by MonkmanMH** [comment]
The problem lies in the source data; I've created a repo on my own git that runs the same code using versions of the original csv files from the Lahman database (both 2013 and 2014). The repo has the RMD file and the two csv data files.

[https://github.com/MonkmanMH/Lahman_package_rstats/tree/master/Appearances](https://github.com/MonkmanMH/Lahman_package_rstats/tree/master/Appearances)

**Comment by friendly** [comment]
This has been fixed
